#!/bin/sh
set -e

# wait for timidity to show up, and connect it to main virtual port
VIRTUAL_PORT="14"

LANG=C
while true; do
  timidity_port=$(aconnect -l | sed -n "s/^client \(.*\): 'TiMidity'.*/\1/p")

  # has timitidy started?
  if [ -z "$timidity_port" ]; then
    echo "No timidity started, waiting"
    sleep 5
    continue
  fi

  # try to connect (can't delimit though between invalid arguments or already connected)
  # TODO: make this more robust (no hardcoded listening port)
  aconnect $VIRTUAL_PORT $timidity_port || true
  return
done
